<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <!-- dependencies -->
    <link rel="stylesheet" href="bibli-utils/koliko/koliko-Regular.css" type="text/css" />
    <link rel="stylesheet" href="bibli-utils/koliko/koliko-Bold.css" type="text/css" />
    <link rel="stylesheet" href="bibli-utils/koliko/koliko-Light.css" type="text/css" />
    <script type="text/javascript" src="bibli-utils/jquery-3.4.1.min.js"></script>
    
    <!-- my files -->
    <link rel="stylesheet" href="bibli-utils/style.css" type="text/css" />
    <script type="text/javascript" src="bibli-utils/script.js"></script>
    <title>Répertoire de contes</title>
</head>
<body>
    
    <?=$output?>
    
</body>
</html>